---
abstract: 'Generalized REST forwarder for MFILE-based frontends'
author:
  - 'Smithfarm <presnypreklad@gmail.com>'
build_requires:
  App::CELL: '0.196'
  Params::Validate: '1.06'
  Test::Fatal: '0'
configure_requires:
  Module::Build: '0.37'
  Software::License: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.150005'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-MFILE
provides:
  App::MFILE:
    file: lib/App/MFILE.pm
    version: '0.175'
  App::MFILE::HTTP:
    file: lib/App/MFILE/HTTP.pm
requires:
  App::CELL: '0.196'
  HTTP::Request::Common: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  Params::Validate: '1.06'
  perl: '5.012'
resources:
  homepage: https://sourceforge.net/projects/mfile/
  license: http://opensource.org/licenses/bsd-license.php
  repository: https://sourceforge.net/p/mfile/code/
version: '0.175'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
